    # Generated by Django 4.1.7 on 2023-02-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Описание')),
                ('image', models.TextField(max_length=3000, verbose_name='Картинка')),
                ('category', models.TextField(choices=[('OTHER', 'Разное'), ('NOTEBOOKS', 'Ноутбуки'), ('CARS', 'Машины'), ('BOARD_GAME', 'Настольные игры'), ('Chemistry', 'Химия')], default='OTHER', max_length=1000, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('remainder', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
